//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.ServiceModel;

// 
// 此源代码由 xsd 自动生成, Version=2.0.50727.3038。
// 

namespace ESB.Core.Schema
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.jn.com/esb/exception/20100329")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.jn.com/esb/exception/20100329", IsNullable = false)]
    [MessageContract(IsWrapped = true)]
    public partial class Root
    {

        private string 异常编码Field;

        private System.DateTime 异常时间Field;

        private string 异常代码Field;

        private string 异常描述Field;

        private string 异常信息Field;

        private string 异常级别Field;

        private string 异常类型Field;

        private string 主机名称Field;

        private string 方法名称Field;

        private string 消息编码Field;

        private string 绑定地址编码Field;

        private string 异常信息状态Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常编码
        {
            get
            {
                return this.异常编码Field;
            }
            set
            {
                this.异常编码Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public System.DateTime 异常时间
        {
            get
            {
                return this.异常时间Field;
            }
            set
            {
                this.异常时间Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常代码
        {
            get
            {
                return this.异常代码Field;
            }
            set
            {
                this.异常代码Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常描述
        {
            get
            {
                return this.异常描述Field;
            }
            set
            {
                this.异常描述Field = value;
            }
        }

        /// <remarks/>
        /// 
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常信息
        {
            get
            {
                return this.异常信息Field;
            }
            set
            {
                this.异常信息Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常级别
        {
            get
            {
                return this.异常级别Field;
            }
            set
            {
                this.异常级别Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常类型
        {
            get
            {
                return this.异常类型Field;
            }
            set
            {
                this.异常类型Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 主机名称
        {
            get
            {
                return this.主机名称Field;
            }
            set
            {
                this.主机名称Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 方法名称
        {
            get
            {
                return this.方法名称Field;
            }
            set
            {
                this.方法名称Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 消息编码
        {
            get
            {
                return this.消息编码Field;
            }
            set
            {
                this.消息编码Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 绑定地址编码
        {
            get
            {
                return this.绑定地址编码Field;
            }
            set
            {
                this.绑定地址编码Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [MessageBodyMember()]
        public string 异常信息状态
        {
            get
            {
                return this.异常信息状态Field;
            }
            set
            {
                this.异常信息状态Field = value;
            }
        }
    }
}