#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JN.ESB.Audit.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="EsbAuditDB")]
	public partial class AuditBusinessDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAuditBusiness(AuditBusiness instance);
    partial void UpdateAuditBusiness(AuditBusiness instance);
    partial void DeleteAuditBusiness(AuditBusiness instance);
    #endregion

		public AuditBusinessDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuditBusinessDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuditBusinessDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AuditBusinessDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AuditBusiness> AuditBusiness
		{
			get
			{
				return this.GetTable<AuditBusiness>();
			}
		}
	}
	
	[Table(Name="dbo.AuditBusiness")]
	public partial class AuditBusiness : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _OID;
		
		private string _HostName;
		
		private string _ServiceName;
		
		private string _MethodName;
		
		private string _ReqBeginTime;
		
		private string _ReqEndTime;
		
		private int _Status;
		
		private string _MessageID;
		
		private string _CallBeginTime;
		
		private string _CallEndTime;
		
		private string _ServiceID;
		
		private string _BusinessID;
		
		private string _BusinessName;
		
		private string _BindingAddress;

        private string _MessageBody;

        private string _ReturnMessageBody;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOIDChanging(string value);
    partial void OnOIDChanged();
    partial void OnHostNameChanging(string value);
    partial void OnHostNameChanged();
    partial void OnServiceNameChanging(string value);
    partial void OnServiceNameChanged();
    partial void OnMethodNameChanging(string value);
    partial void OnMethodNameChanged();
    partial void OnReqBeginTimeChanging(string value);
    partial void OnReqBeginTimeChanged();
    partial void OnReqEndTimeChanging(string value);
    partial void OnReqEndTimeChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnMessageIDChanging(string value);
    partial void OnMessageIDChanged();
    partial void OnMessageBodyChanging(string value);
    partial void OnMessageBodyChanged();
    partial void OnCallBeginTimeChanging(string value);
    partial void OnCallBeginTimeChanged();
    partial void OnCallEndTimeChanging(string value);
    partial void OnCallEndTimeChanged();
    partial void OnServiceIDChanging(string value);
    partial void OnServiceIDChanged();
    partial void OnBusinessIDChanging(string value);
    partial void OnBusinessIDChanged();
    partial void OnBusinessNameChanging(string value);
    partial void OnBusinessNameChanged();
    partial void OnBindingAddressChanging(string value);
    partial void OnBindingAddressChanged();
    partial void OnReturnMessageBodyChanging(string value);
    partial void OnReturnMessageBodyChanged();
    #endregion
		
		public AuditBusiness()
		{
			OnCreated();
		}
		
		[Column(Storage="_OID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string OID
		{
			get
			{
				return this._OID;
			}
			set
			{
				if ((this._OID != value))
				{
					this.OnOIDChanging(value);
					this.SendPropertyChanging();
					this._OID = value;
					this.SendPropertyChanged("OID");
					this.OnOIDChanged();
				}
			}
		}
		
		[Column(Storage="_HostName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HostName
		{
			get
			{
				return this._HostName;
			}
			set
			{
				if ((this._HostName != value))
				{
					this.OnHostNameChanging(value);
					this.SendPropertyChanging();
					this._HostName = value;
					this.SendPropertyChanged("HostName");
					this.OnHostNameChanged();
				}
			}
		}
		
		[Column(Storage="_ServiceName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this.OnServiceNameChanging(value);
					this.SendPropertyChanging();
					this._ServiceName = value;
					this.SendPropertyChanged("ServiceName");
					this.OnServiceNameChanged();
				}
			}
		}
		
		[Column(Storage="_MethodName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MethodName
		{
			get
			{
				return this._MethodName;
			}
			set
			{
				if ((this._MethodName != value))
				{
					this.OnMethodNameChanging(value);
					this.SendPropertyChanging();
					this._MethodName = value;
					this.SendPropertyChanged("MethodName");
					this.OnMethodNameChanged();
				}
			}
		}
		
		[Column(Storage="_ReqBeginTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReqBeginTime
		{
			get
			{
				return this._ReqBeginTime;
			}
			set
			{
				if ((this._ReqBeginTime != value))
				{
					this.OnReqBeginTimeChanging(value);
					this.SendPropertyChanging();
					this._ReqBeginTime = value;
					this.SendPropertyChanged("ReqBeginTime");
					this.OnReqBeginTimeChanged();
				}
			}
		}
		
		[Column(Storage="_ReqEndTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReqEndTime
		{
			get
			{
				return this._ReqEndTime;
			}
			set
			{
				if ((this._ReqEndTime != value))
				{
					this.OnReqEndTimeChanging(value);
					this.SendPropertyChanging();
					this._ReqEndTime = value;
					this.SendPropertyChanged("ReqEndTime");
					this.OnReqEndTimeChanged();
				}
			}
		}
		
		[Column(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[Column(Storage="_MessageID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MessageID
		{
			get
			{
				return this._MessageID;
			}
			set
			{
				if ((this._MessageID != value))
				{
					this.OnMessageIDChanging(value);
					this.SendPropertyChanging();
					this._MessageID = value;
					this.SendPropertyChanged("MessageID");
					this.OnMessageIDChanged();
				}
			}
		}
		
		[Column(Storage="_CallBeginTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CallBeginTime
		{
			get
			{
				return this._CallBeginTime;
			}
			set
			{
				if ((this._CallBeginTime != value))
				{
					this.OnCallBeginTimeChanging(value);
					this.SendPropertyChanging();
					this._CallBeginTime = value;
					this.SendPropertyChanged("CallBeginTime");
					this.OnCallBeginTimeChanged();
				}
			}
		}
		
		[Column(Storage="_CallEndTime", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CallEndTime
		{
			get
			{
				return this._CallEndTime;
			}
			set
			{
				if ((this._CallEndTime != value))
				{
					this.OnCallEndTimeChanging(value);
					this.SendPropertyChanging();
					this._CallEndTime = value;
					this.SendPropertyChanged("CallEndTime");
					this.OnCallEndTimeChanged();
				}
			}
		}
		
		[Column(Storage="_ServiceID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ServiceID
		{
			get
			{
				return this._ServiceID;
			}
			set
			{
				if ((this._ServiceID != value))
				{
					this.OnServiceIDChanging(value);
					this.SendPropertyChanging();
					this._ServiceID = value;
					this.SendPropertyChanged("ServiceID");
					this.OnServiceIDChanged();
				}
			}
		}
		
		[Column(Storage="_BusinessID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BusinessID
		{
			get
			{
				return this._BusinessID;
			}
			set
			{
				if ((this._BusinessID != value))
				{
					this.OnBusinessIDChanging(value);
					this.SendPropertyChanging();
					this._BusinessID = value;
					this.SendPropertyChanged("BusinessID");
					this.OnBusinessIDChanged();
				}
			}
		}
		
		[Column(Storage="_BusinessName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BusinessName
		{
			get
			{
				return this._BusinessName;
			}
			set
			{
				if ((this._BusinessName != value))
				{
					this.OnBusinessNameChanging(value);
					this.SendPropertyChanging();
					this._BusinessName = value;
					this.SendPropertyChanged("BusinessName");
					this.OnBusinessNameChanged();
				}
			}
        }

        [Column(Storage = "_BindingAddress", DbType = "NVarChar(200) NOT NULL", CanBeNull = false)]
        public string BindingAddress
        {
            get
            {
                return this._BindingAddress;
            }
            set
            {
                if ((this._BindingAddress != value))
                {
                    this.OnBindingAddressChanging(value);
                    this.SendPropertyChanging();
                    this._BindingAddress = value;
                    this.SendPropertyChanged("BindingAddress");
                    this.OnBindingAddressChanged();
                }
            }
        }

        [Column(Storage = "_MessageBody", DbType = "NText", CanBeNull = false)]
        public string MessageBody
        {
            get
            {
                return this._MessageBody;
            }
            set
            {
                if ((this._BindingAddress != value))
                {
                    this.OnBindingAddressChanging(value);
                    this.SendPropertyChanging();
                    this._BindingAddress = value;
                    this.SendPropertyChanged("MessageBody");
                    this.OnBindingAddressChanged();
                }
            }
        }

        [Column(Storage = "_ReturnMessageBody", DbType = "NText", CanBeNull = false)]
        public string ReturnMessageBody
        {
            get
            {
                return this._ReturnMessageBody;
            }
            set
            {
                if ((this._BindingAddress != value))
                {
                    this.OnBindingAddressChanging(value);
                    this.SendPropertyChanging();
                    this._BindingAddress = value;
                    this.SendPropertyChanged("ReturnMessageBody");
                    this.OnBindingAddressChanged();
                }
            }
        }
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
